name: Trivy Scan
description: Scan container image with Trivy
inputs:
  image:
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Trivy
      run: |
        wget https://github.com/aquasecurity/trivy/releases/download/v0.44.1/trivy_0.44.1_Linux-64bit.deb
        sudo dpkg -i trivy_0.44.1_Linux-64bit.deb
      shell: bash


    - name: Scan image
      run: |
        trivy image --severity HIGH,CRITICAL --no-progress ${{ inputs.image }}
      shell: bash
