{{- if and .Values.decode .Values.multinode }}
apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: {{ include "llm-d-modelservice.fullname" . }}-decode
  labels:
    {{- include "llm-d-modelservice.labels" . | nindent 4 }}
    {{- include "llm-d-modelservice.decodelabels" . | nindent 4 }}
spec:
  {{- if not .Values.decode.autoscaling.enabled }}
  replicas: {{ default 1 .Values.decode.replicas }}
  {{- end }}
  leaderWorkerTemplate:
    size: {{ int (include "llm-d-modelservice.dataParallelism" .Values.decode.parallelism) }}
    leaderTemplate:
      metadata:
        labels:
          {{- include "llm-d-modelservice.decodelabels" . | nindent 10 }}
      spec:
        {{- with .Values.routing }}
        {{ (include "llm-d-modelservice.routingProxy" .) | nindent 8 }}
        {{- end }}
        {{- (include "llm-d-modelservice.modelPod" .) | nindent 6 }}
        {{- with .Values.decode.containers }}
        containers:
          {{- range . }}
          {{- (include "llm-d-modelservice.container" (dict "container" . "authSecretName" $.Values.modelArtifacts.authSecretName "parallelism" $.Values.decode.parallelism)) | nindent 10 }}
          {{- end }}
        {{- end }}
      volumes:
      {{- with .Values.decode.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- include "llm-d-modelservice.mountModelVolumeVolumes" . | nindent 10 }} 

    workerTemplate:
      metadata:
        labels:
          {{- include "llm-d-modelservice.decodelabels" . | nindent 10 }}
      spec:
        {{- with .Values.decode.containers }}
        containers:
          {{- range . }}
          {{- (include "llm-d-modelservice.container" (dict "container" . "authSecretName" $.Values.modelArtifacts.authSecretName "parallelism" $.Values.decode.parallelism)) | nindent 10 }}
          {{- end }}
        {{- end }}
      volumes:
      {{- with .Values.decode.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- include "llm-d-modelservice.mountModelVolumeVolumes" . | nindent 10 }} 

{{- end }}
