{{- if .Values.decode }}
{{- $parallelism := (include "llm-d-modelservice.parallelism" .Values.decode.parallelism) | fromYaml -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "llm-d-modelservice.fullname" . }}-decode
  labels:
    {{- include "llm-d-modelservice.labels" . | nindent 4 }}
spec:
  replicas: {{ default 1 .Values.decode.replicas }}
  selector:
    matchLabels:
      {{- include "llm-d-modelservice.decodelabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "llm-d-modelservice.decodelabels" . | nindent 8 }}
    spec:
      {{- with .Values.decode.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "llm-d-modelservice.pdServiceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.decode.acceleratorTypes }}
      {{- include "llm-d-modelservice.acceleratorTypes" . | nindent 6 }}
      {{- end }}
      {{- /* Sidecar init container */}}
      {{- with .Values.routing }}
        {{ (include "llm-d-modelservice.routingProxy" .) | nindent 6 }}
      {{- end }}    
      {{- /* User's other init containesr */}}
      {{- with .Values.decode.initContainers }}
        {{- toYaml . | nindent 8 }}
      {{- end }}   
      {{- /* range $.Values.decode.containers */}}
      {{- with .Values.decode.containers }}
      containers:
      {{- range . }}
      - name: {{ default "vllm" .name }}
        image: {{ required "image of container is required" .image }}
        {{- with .securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .imagePullPolicy }}
        imagePullPolicy: {{ . }}
        {{- end }}
        {{- with .command }}
        command:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .args }}
        args:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- /* insert user's env for this container */}}
        {{- if or .env .mountModelVolume }}
        env:
        {{- end }}
        {{- with .env }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- /* insert envs based on what modelArtifact prefix */}}
        {{- if .mountModelVolume }}
          - name: HF_HOME
            value: /model-cache
          {{- with $.Values.modelArtifacts.authSecretName }}
          - name: HF_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ . }}
                key: HF_TOKEN
          {{- end }}
        {{- end }}
        {{- with .livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- include "llm-d-modelservice.resources" (dict "resources" .resources "parallelism" $parallelism) | nindent 8 }}
        {{- /* volumeMount */}}
        {{- include "llm-d-modelservice.mountModelVolumeVolumeMounts" . | nindent 8 }}
        {{- end }}
      {{- end }}
      volumes:
      {{- with .Values.decode.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end -}}
      {{- include "llm-d-modelservice.mountModelVolumeVolumes" . | nindent 8 }} 
{{- end }}