{{- if and .Values.decode (not .Values.multinode) }}
{{- $parallelism := (include "llm-d-modelservice.parallelism" .Values.decode.parallelism) | fromYaml -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "llm-d-modelservice.fullname" . }}-decode
  labels:
    {{- include "llm-d-modelservice.labels" . | nindent 4 }}
spec:
  replicas: {{ default 1 .Values.decode.replicas }}
  selector:
    matchLabels:
      {{- include "llm-d-modelservice.decodelabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "llm-d-modelservice.decodelabels" . | nindent 8 }}
    spec:
      {{- with .Values.routing }}
      {{- (include "llm-d-modelservice.routingProxy" .) | nindent 6 }}
      {{- end }}
      {{- (include "llm-d-modelservice.modelPod" .) | nindent 4 }}
      {{- with .Values.decode.containers }}
      containers:
        {{- range . }}
        {{- (include "llm-d-modelservice.container" (dict "container" . "authSecretName" $.Values.modelArtifacts.authSecretName "parallelism" $parallelism)) | nindent 8 }}
        {{- end }}
      {{- end }}
      volumes:
      {{- with .Values.decode.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- include "llm-d-modelservice.mountModelVolumeVolumes" . | nindent 8 }} 
{{- end }}