{{- if .Values.endpointPicker -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "llm-d-modelservice.eppServiceAccountName" . }}
  labels:
    {{- include "llm-d-modelservice.labels" . | nindent 4 }}
{{- end }}
