{{- if .Values.inferencePool }}
apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferencePool
metadata:
  name: {{ include "llm-d-modelservice.fullname" . }}-inference-pool
  namespace: {{ .Release.Namespace }}
spec:
  extensionRef:
    failureMode: FailClose
    group: ""
    kind: Service
    name: {{ include "llm-d-modelservice.fullname" . }}-epp-service
  selector:
    {{- include "llm-d-modelservice.pdlabels" . | nindent 4 }}
  targetPortNumber: 8000
{{- end }}
