{{- if .Values.prefill }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "llm-d-modelservice.fullname" . }}-prefill
  labels:
    {{- include "llm-d-modelservice.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.prefill.replicas }}
  selector:
    matchLabels:
      {{- include "llm-d-modelservice.prefilllabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "llm-d-modelservice.prefilllabels" . | nindent 8 }}
    spec:
      {{- with .Values.prefill.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "llm-d-modelservice.pdServiceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.prefill.acceleratorTypes }}
      {{- include "llm-d-modelservice.acceleratorTypes" . | nindent 6 }}
      {{- end }}
      {{- /* range $.Values.prefill.containers */}}
      {{- with .Values.prefill.containers }}
      containers:
      {{- range . }}
        - name: {{ .name }}
          image: {{ .image }}
          {{- with .securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .imagePullPolicy }}
          imagePullPolicy: {{ . }}
          {{- end }}
          {{- with .command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- /* insert user's env for this container */}}
          {{- if or .env .mountModelVolume}}
          env:
          {{- end }}
          {{- with .env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- /* insert envs based on what modelArtifact prefix */}}
          {{- if .mountModelVolume }}
            - name: HF_HOME
              value: /model-cache
            {{- with $.Values.modelArtifacts.authSecretName }}
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ . }}
                  key: HF_TOKEN
            {{- end }}
          {{- end }}
          {{- with .livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- /* volumeMount */}}
          {{- if or .volumeMounts .mountModelVolume }}
          volumeMounts:
          {{- end -}}
          {{- /* user supplied volume mount in values */}}
          {{- with .volumeMounts }}
            {{- toYaml . | nindent 14 }}
          {{- end }}
          {{- /* what we add if mounModelVolume is true */}}
          {{- if .mountModelVolume }}
            - name: model-storage
              mountPath: /model-cache
          {{- end }}
        {{- end }}
      {{- end }}
      volumes:
      {{- with .Values.prefill.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if eq .Values.modelArtifacts.prefix "hf" }}
        - name: model-storage
          emptyDir: 
            sizeLimit: {{ default "0" .Values.modelArtifacts.size }}
      {{- else if eq .Values.modelArtifacts.prefix "pvc" }}
        - name: model-storage
          persistentVolumeClaim:
            claimName: {{ .Values.modelArtifacts.artifact }}
            readOnly: true
      {{- else if eq .Values.modelArtifacts.prefix "oci" }}
        - name: model-storage
          image:
            reference: {{ .Values.modelArtifacts.artifact }}
            {{- with .Values.modelArtifacts.imagePullPolicy }} 
            pullPolicy: {{ . }}
            {{- end }}
      {{- end }}
{{- end }}