{{- $parallelism := (include "llm-d-modelservice.parallelism" .Values.decode.parallelism) | fromYaml -}}
{{- if .Values.prefill }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "llm-d-modelservice.fullname" . }}-prefill
  labels:
    {{- include "llm-d-modelservice.labels" . | nindent 4 }}
spec:
  replicas: {{ default 1 .Values.prefill.replicas }}
  selector:
    matchLabels:
      {{- include "llm-d-modelservice.prefilllabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "llm-d-modelservice.prefilllabels" . | nindent 8 }}
    spec:
      {{- with .Values.prefill.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "llm-d-modelservice.pdServiceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.prefill.acceleratorTypes }}
      {{- include "llm-d-modelservice.acceleratorTypes" . | nindent 6 }}
      {{- end }}
      {{- /* range $.Values.prefill.containers */}}
      {{- with .Values.prefill.containers }}
      containers:
      {{- range . }}
        - name: {{ .name }}
          image: {{ .image }}
          {{- with .securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .imagePullPolicy }}
          imagePullPolicy: {{ . }}
          {{- end }}
          {{- with .command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- /* insert user's env for this container */}}
          {{- if or .env .mountModelVolume}}
          env:
          {{- end }}
          {{- with .env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- /* insert envs based on what modelArtifact prefix */}}
          {{- if .mountModelVolume }}
            - name: HF_HOME
              value: /model-cache
            {{- with $.Values.modelArtifacts.authSecretName }}
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ . }}
                  key: HF_TOKEN
            {{- end }}
          {{- end }}
          {{- with .livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .resources }}
          resources:
            limits:
              {{- if and .resources .resources.limits }}
              {{- omit .resources.limits "nvidia.com/gpu"  | toYaml | nindent 14 }}
              {{- end }}
              nvidia.com/gpu: "{{ $parallelism.tensor }}"
            requests:
              {{- if and .resources .resources.limits }}
              {{- omit .resources.requests "nvidia.com/gpu" | toYaml | nindent 14 }}
              {{- end }}
              nvidia.com/gpu: "{{ $parallelism.tensor }}"
          {{- end }}
          {{- /* volumeMount */}}
          {{- include "llm-d-modelservice.mountModelVolumeVolumeMounts" . | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- /* insert volumes for this deployment */}}
      volumes:
      {{- with .Values.prefill.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- include "llm-d-modelservice.mountModelVolumeVolumes" . | nindent 8 }}
{{- end }}