apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "llm-d-modelservice.fullname" . }}-epp-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ required "role for inference schedule required" .Values.endpointPicker.permissions }}
subjects:
- kind: ServiceAccount
  name: {{ include "llm-d-modelservice.eppServiceAccountName" . }}