name: Go Test
description: Run Ginkgo tests
runs:
  using: "composite"
  steps:
    - run: |
        echo "Installing Ginkgo..."
        go install github.com/onsi/ginkgo/ginkgo@latest
        export PATH=$PATH:$(go env GOPATH)/bin
        echo "Ginkgo installed:"
        ginkgo version
        echo "Running tests with Ginkgo..."
        go env -w GOFLAGS=-buildvcs=false
        make test
      shell: bash
