
# Make image pull policy always -- dev deploy requires this
- op: add
  path: /spec/template/spec/containers/0/imagePullPolicy
  value: Always

# Add image pull secret
- op: add
  path: /spec/template/spec/imagePullSecrets
  value: 
  - name: quay-secret-llm-d

- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --epp-cluster-role=epp-cluster-role
