
# Make image pull policy Always -- dev images require this
- op: add
  path: /spec/template/spec/containers/0/imagePullPolicy
  value: Always

# Add image pull secret
- op: add
  path: /spec/template/spec/imagePullSecrets
  value: 
  - name: $IMAGE_PULL_SECRET

# to configure pull secrets for pd and epp pods, uncomment and set environemnt variables
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --pd-pull-secrets=$PD_PULL_SECRETS
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --epp-pull-secrets=$EPP_PULL_SECRETS

# Make image pull policy configurable -- e.g., Always, Never, IfNotPresent
- op: add
  path: /spec/template/spec/containers/0/imagePullPolicy
  value: ${IMAGE_PULL_POLICY}
